### ISSUE TITLE
Is 10 epoches enough for this experiment?

### ISSUE THREAD

**Issue by Ehzoahis** [facebookresearch/InvarianceUnitTests#2]
https://github.com/facebookresearch/InvarianceUnitTests/blob/508504c66f3d2c951f621ea38e2e36c040c223e6/reproduce_results.sh#L45

For the sweeping environments experiment, is 10 epochs here intended? Since when I tried to reproduce the code, even the Oracle will not reach zero error rate.

**Comment by benjaminaubin** [comment]
Dear Ehzoahis, 

The number of iterations `--num_iterations 10` in this file is not enough indeed (this was meant to debug and run all the examples quickly to make sure everything works correctly).  I will correct this. Thanks for noticing.
